namespace Komodo.Core.Engine.Input
{
    /// <summary>
    /// Defines all button, keyboard, and mouse inputs.
    /// </summary>
    public enum Inputs
    {
        Undefined,
        // Buttons
        ButtonA,
        ButtonB,
        ButtonDown,
        ButtonHome,
        ButtonL1,
        ButtonL2,
        ButtonL3,
        ButtonLeft,
        ButtonR1,
        ButtonR2,
        ButtonR3,
        ButtonRight,
        ButtonSelect,
        ButtonStart,
        ButtonUp,
        ButtonX,
        ButtonY,
        // Keys
        KeyA,
        KeyB,
        KeyBackSpace,
        KeyC,
        KeyCapsLock,
        KeyD,
        KeyDecimal,
        KeyDelete,
        KeyDown,
        KeyE,
        KeyEnter,
        KeyEscape,
        KeyF,
        KeyF1,
        KeyF10,
        KeyF11,
        KeyF12,
        KeyF2,
        KeyF3,
        KeyF4,
        KeyF5,
        KeyF6,
        KeyF7,
        KeyF8,
        KeyF9,
        KeyG,
        KeyH,
        KeyI,
        KeyJ,
        KeyK,
        KeyL,
        KeyLeft,
        KeyLeftAlt,
        KeyLeftControl,
        KeyLeftShift,
        KeyM,
        KeyN,
        KeyO,
        KeyP,
        KeyQ,
        KeyR,
        KeyRight,
        KeyRightAlt,
        KeyRightControl,
        KeyRightShift,
        KeyS,
        KeyT,
        KeyTab,
        KeyU,
        KeyUp,
        KeyV,
        KeyW,
        KeyX,
        KeyY,
        KeyZ,
        // Mouse
        MouseLeftClick,
        MouseMiddleClick,
        MouseRightClick,
    }
}