[<AutoOpen>]
module Komodo.Backends.OpenGL.Api.Constants.OpenGL3_2

[<Literal>]
let GL_CONTEXT_CORE_PROFILE_BIT = 0x00000001u
[<Literal>]
let GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 0x00000002u
[<Literal>]
let GL_LINES_ADJACENCY = 0x000Au
[<Literal>]
let GL_LINE_STRIP_ADJACENCY = 0x000Bu
[<Literal>]
let GL_TRIANGLES_ADJACENCY = 0x000Cu
[<Literal>]
let GL_TRIANGLE_STRIP_ADJACENCY = 0x000Du
[<Literal>]
let GL_PROGRAM_POINT_SIZE = 0x8642u
[<Literal>]
let GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29u
[<Literal>]
let GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7u
[<Literal>]
let GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8u
[<Literal>]
let GL_GEOMETRY_SHADER = 0x8DD9u
[<Literal>]
let GL_GEOMETRY_VERTICES_OUT = 0x8916u
[<Literal>]
let GL_GEOMETRY_INPUT_TYPE = 0x8917u
[<Literal>]
let GL_GEOMETRY_OUTPUT_TYPE = 0x8918u
[<Literal>]
let GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDFu
[<Literal>]
let GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0u
[<Literal>]
let GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1u
[<Literal>]
let GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122u
[<Literal>]
let GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123u
[<Literal>]
let GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124u
[<Literal>]
let GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125u
[<Literal>]
let GL_CONTEXT_PROFILE_MASK = 0x9126u
[<Literal>]
let GL_DEPTH_CLAMP = 0x864Fu
[<Literal>]
let GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = 0x8E4Cu
[<Literal>]
let GL_FIRST_VERTEX_CONVENTION = 0x8E4Du
[<Literal>]
let GL_LAST_VERTEX_CONVENTION = 0x8E4Eu
[<Literal>]
let GL_PROVOKING_VERTEX = 0x8E4Fu
[<Literal>]
let GL_TEXTURE_CUBE_MAP_SEAMLESS = 0x884Fu
[<Literal>]
let GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111u
[<Literal>]
let GL_OBJECT_TYPE = 0x9112u
[<Literal>]
let GL_SYNC_CONDITION = 0x9113u
[<Literal>]
let GL_SYNC_STATUS = 0x9114u
[<Literal>]
let GL_SYNC_FLAGS = 0x9115u
[<Literal>]
let GL_SYNC_FENCE = 0x9116u
[<Literal>]
let GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117u
[<Literal>]
let GL_UNSIGNALED = 0x9118u
[<Literal>]
let GL_SIGNALED = 0x9119u
[<Literal>]
let GL_ALREADY_SIGNALED = 0x911Au
[<Literal>]
let GL_TIMEOUT_EXPIRED = 0x911Bu
[<Literal>]
let GL_CONDITION_SATISFIED = 0x911Cu
[<Literal>]
let GL_WAIT_FAILED = 0x911Du
[<Literal>]
let GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFFUL
[<Literal>]
let GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001u
[<Literal>]
let GL_SAMPLE_POSITION = 0x8E50u
[<Literal>]
let GL_SAMPLE_MASK = 0x8E51u
[<Literal>]
let GL_SAMPLE_MASK_VALUE = 0x8E52u
[<Literal>]
let GL_MAX_SAMPLE_MASK_WORDS = 0x8E59u
[<Literal>]
let GL_TEXTURE_2D_MuTISAMPLE = 0x9100u
[<Literal>]
let GL_PROXY_TEXTURE_2D_MuTISAMPLE = 0x9101u
[<Literal>]
let GL_TEXTURE_2D_MuTISAMPLE_ARRAY = 0x9102u
[<Literal>]
let GL_PROXY_TEXTURE_2D_MuTISAMPLE_ARRAY = 0x9103u
[<Literal>]
let GL_TEXTURE_BINDING_2D_MuTISAMPLE = 0x9104u
[<Literal>]
let GL_TEXTURE_BINDING_2D_MuTISAMPLE_ARRAY = 0x9105u
[<Literal>]
let GL_TEXTURE_SAMPLES = 0x9106u
[<Literal>]
let GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107u
[<Literal>]
let GL_SAMPLER_2D_MuTISAMPLE = 0x9108u
[<Literal>]
let GL_INT_SAMPLER_2D_MuTISAMPLE = 0x9109u
[<Literal>]
let GL_UNSIGNED_INT_SAMPLER_2D_MuTISAMPLE = 0x910Au
[<Literal>]
let GL_SAMPLER_2D_MuTISAMPLE_ARRAY = 0x910Bu
[<Literal>]
let GL_INT_SAMPLER_2D_MuTISAMPLE_ARRAY = 0x910Cu
[<Literal>]
let GL_UNSIGNED_INT_SAMPLER_2D_MuTISAMPLE_ARRAY = 0x910Du
[<Literal>]
let GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910Eu
[<Literal>]
let GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910Fu
[<Literal>]
let GL_MAX_INTEGER_SAMPLES = 0x9110u