[<AutoOpen>]
module Komodo.Backends.OpenGL.Api.Constants.OpenGL3_1

[<Literal>]
let GL_SAMPLER_2D_RECT = 0x8B63u
[<Literal>]
let GL_SAMPLER_2D_RECT_SHADOW = 0x8B64u
[<Literal>]
let GL_SAMPLER_BUFFER = 0x8DC2u
[<Literal>]
let GL_INT_SAMPLER_2D_RECT = 0x8DCDu
[<Literal>]
let GL_INT_SAMPLER_BUFFER = 0x8DD0u
[<Literal>]
let GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5u
[<Literal>]
let GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8u
[<Literal>]
let GL_TEXTURE_BUFFER = 0x8C2Au
[<Literal>]
let GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2Bu
[<Literal>]
let GL_TEXTURE_BINDING_BUFFER = 0x8C2Cu
[<Literal>]
let GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2Du
[<Literal>]
let GL_TEXTURE_RECTANGLE = 0x84F5u
[<Literal>]
let GL_TEXTURE_BINDING_RECTANGLE = 0x84F6u
[<Literal>]
let GL_PROXY_TEXTURE_RECTANGLE = 0x84F7u
[<Literal>]
let GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8u
[<Literal>]
let GL_R8_SNORM = 0x8F94u
[<Literal>]
let GL_RG8_SNORM = 0x8F95u
[<Literal>]
let GL_RGB8_SNORM = 0x8F96u
[<Literal>]
let GL_RGBA8_SNORM = 0x8F97u
[<Literal>]
let GL_R16_SNORM = 0x8F98u
[<Literal>]
let GL_RG16_SNORM = 0x8F99u
[<Literal>]
let GL_RGB16_SNORM = 0x8F9Au
[<Literal>]
let GL_RGBA16_SNORM = 0x8F9Bu
[<Literal>]
let GL_SIGNED_NORMALIZED = 0x8F9Cu
[<Literal>]
let GL_PRIMITIVE_RESTART = 0x8F9Du
[<Literal>]
let GL_PRIMITIVE_RESTART_INDEX = 0x8F9Eu
[<Literal>]
let GL_COPY_READ_BUFFER = 0x8F36u
[<Literal>]
let GL_COPY_WRITE_BUFFER = 0x8F37u
[<Literal>]
let GL_UNIFORM_BUFFER = 0x8A11u
[<Literal>]
let GL_UNIFORM_BUFFER_BINDING = 0x8A28u
[<Literal>]
let GL_UNIFORM_BUFFER_START = 0x8A29u
[<Literal>]
let GL_UNIFORM_BUFFER_SIZE = 0x8A2Au
[<Literal>]
let GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2Bu
[<Literal>]
let GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2Cu
[<Literal>]
let GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2Du
[<Literal>]
let GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2Eu
[<Literal>]
let GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2Fu
[<Literal>]
let GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30u
[<Literal>]
let GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31u
[<Literal>]
let GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32u
[<Literal>]
let GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33u
[<Literal>]
let GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34u
[<Literal>]
let GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35u
[<Literal>]
let GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36u
[<Literal>]
let GL_UNIFORM_TYPE = 0x8A37u
[<Literal>]
let GL_UNIFORM_SIZE = 0x8A38u
[<Literal>]
let GL_UNIFORM_NAME_LENGTH = 0x8A39u
[<Literal>]
let GL_UNIFORM_BLOCK_INDEX = 0x8A3Au
[<Literal>]
let GL_UNIFORM_OFFSET = 0x8A3Bu
[<Literal>]
let GL_UNIFORM_ARRAY_STRIDE = 0x8A3Cu
[<Literal>]
let GL_UNIFORM_MATRIX_STRIDE = 0x8A3Du
[<Literal>]
let GL_UNIFORM_IS_ROW_MAJOR = 0x8A3Eu
[<Literal>]
let GL_UNIFORM_BLOCK_BINDING = 0x8A3Fu
[<Literal>]
let GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40u
[<Literal>]
let GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41u
[<Literal>]
let GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42u
[<Literal>]
let GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43u
[<Literal>]
let GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44u
[<Literal>]
let GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45u
[<Literal>]
let GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46u
[<Literal>]
let GL_INVALID_INDEX = 0xFFFFFFFFu